### ISSUE TITLE
Embed link goes to wrong page

### ISSUE THREAD

**Issue by jacany** [Fallen-Networks/sourcebans-pp#1]
Upon clicking on the link for the embed, it goes to the homepage on the punishments site. Instead this should go to the information on that punishment. Also, change "View on Sourcebans" to "View on Punishments" because we do not use the default sourcebans panel.

**Comment by Damien111** [comment]
This has nothing to do with this set of plugins, nor will it ever be fixed. The punishments list on discord is simply so we can see if someone goes on a mass punishment spree, nothing more.
